### ISSUE TITLE
On systems with >8 cores, Gaffer lacks borders

### ISSUE THREAD

**Issue by srcshelton** [Shakshi3104/Gaufre#2]
With additional cores, the window size needs to be expanded or the gauge-width reduced:

![Screenshot 2022-01-20 at 5 51 21 pm](https://user-images.githubusercontent.com/179397/150394529-1d724f0a-950e-44f0-9e5b-aff640488820.png)

N.B. There should be 16 cores shown - the Gaffer window only fits 10!

**Comment by Shakshi3104** [comment]
Hi. Thanks for the feedback.

I didn't notice that problem because the Mac I owned had 8 cores.
I will fix it.

**Comment by Shakshi3104** [comment]
I fixed this issue. Please use [Gaufre v1.2.0](https://github.com/Shakshi3104/Gaufre/releases/tag/1.2.0) !
